import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {NavLink,Routes,Route,Navigate} from 'react-router-dom';
import {Home,Compass,CalendarDays,Users,UserRound,LogOut} from 'lucide-react';
import {request,ApiError,type Profile,type Organization} from './api';
import AuthPage from './AuthPage';import OrganizationPage from './OrganizationPage';import ProfilePage from './ProfilePage';
import {Panel,Empty,ErrorMessage,Action} from './ui';
export default function App(){const query=useQueryClient();const [selected,setSelected]=useState<number>();
 const me=useQuery({queryKey:['me'],queryFn:()=>request<Profile>('/me')});
 const organizations=useQuery({queryKey:['organizations'],queryFn:()=>request<Organization[]>('/organizations'),enabled:!!me.data});
 if(me.isPending)return <main className="loading">UCC를 불러오고 있어요…</main>;
 if(me.error){if(me.error instanceof ApiError&&me.error.status===401)return <AuthPage/>;return <main><ErrorMessage error={me.error}/><Action label="다시 시도" onAction={()=>me.refetch()}/></main>}
 const user=me.data!;const org=organizations.data?.find(o=>o.id===selected)||organizations.data?.[0];
 return <div className="shell"><aside><NavLink to="/" className="brand"><img src="/ucc-logo.png" alt=""/><div><strong>UCC</strong><small>유크크</small></div></NavLink><p className="eyebrow">캠퍼스의 이야기를 잇다</p><nav>{[['/','홈',Home],['/discover','찾기',Compass],['/calendar','캘린더',CalendarDays],['/organization','소속',Users],['/profile','나',UserRound]].map(([to,label,Icon])=>{const I=Icon as typeof Home;return <NavLink key={to as string} to={to as string} end><I size={19}/>{label as string}</NavLink>})}</nav><div className="aside-bottom"><div className="list-row"><span className="avatar small">{user.name[0]}</span><div><strong>{user.name}</strong><small>{user.department||'학과 미등록'}</small></div></div><Action label="로그아웃" onAction={async()=>{await request('/auth/logout','POST');query.clear();await me.refetch()}}/></div></aside><div className="workspace"><header><div><span className="eyebrow">UNIVERSITY CAMPUS CORE</span><p>함께 만들고, 다음으로 이어가요.</p></div><select aria-label="학생회 선택" value={org?.id||''} onChange={e=>setSelected(Number(e.target.value))}><option value="" disabled>학생회 선택</option>{organizations.data?.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></header><main><ErrorMessage error={organizations.error}/><Routes><Route path="/" element={<><div className="page-heading"><h1>{user.name}님, 반가워요.</h1><p>우리 학생회의 오늘을 확인해요.</p></div><Panel title={org?.name||'학생회를 시작해 보세요'}><Empty>행사와 모집을 이곳에서 이어갈 수 있어요.</Empty><NavLink to="/organization" className="primary link-button">소속에서 보기</NavLink></Panel></>}/><Route path="/organization" element={<OrganizationPage key={org?.id} org={org} onSelect={setSelected}/>}/><Route path="/profile" element={<ProfilePage user={user}/>}/><Route path="/discover" element={<Panel title="찾기"><Empty>AI FIND · 팀 구하기 · 동아리 기능은 준비 중이에요.</Empty></Panel>}/><Route path="/calendar" element={<Panel title="캘린더"><Empty>회의와 행사 일정을 연결할 예정이에요.</Empty></Panel>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div></div>
}
